name: Hello Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:  [ "main" ]
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir mensagem de in√≠cio
        run: echo "Pipeline iniciado com sucesso"